spring.application.name=SpringAudiJPA
# CONGIURACION DE LA BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/jpa_audit_db
spring.datasource.username=root
spring.datasource.password=221206
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#CONFIGURACION DE HIBERNATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true